version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - echo "public repo1"
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
    - build.info
