version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - aws codebuild batch-get-builds --ids $CODEBUILD_BUILD_ID >> build.info
      - $CODEBUILD_RESOLVED_SOURCE_VERSION >> build.info
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
    - build.info
